### ISSUE TITLE
creating functions lab

### ISSUE THREAD

**Issue by asik193** [learn-co-curriculum/dsc-creating-functions-lab#2]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by hoffm386** [comment]
Not sure what issue you were trying to flag here; the issue text as submitted is just the template. Closing this out.
